version: '3.8'

services:
  futurnod-researcher:
    build: .
    image: futurnod-researcher
    container_name: futurnod-researcher
    ports:
      - "8000:8000"
    volumes:
      - ./results:/app/results
      - ./logs:/app/logs
      - ./.env:/app/.env
      - ./ssl_certs:/app/ssl_certs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - futurnod-network

networks:
  futurnod-network:
    driver: bridge
